/**
 * Supabase Edge Function: exports-create
 * Creates an export job and processes it (PDF/bundle).
 * POST /functions/v1/exports-create
 * Body: CreateExportPayload
 * Returns: { jobId, status }
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

type PaperSize = 'A4' | 'Letter' | 'Legal'
type Orientation = 'portrait' | 'landscape'

interface IncludedSections {
  studySheet?: boolean
  flashcards?: boolean
  answers?: boolean
  notes?: boolean
}

function renderExportHtml(
  study: { topic?: string },
  payload: Record<string, unknown>,
  opts: { watermark?: boolean; paperSize?: PaperSize; orientation?: Orientation; include?: IncludedSections }
): string {
  const include = opts.include ?? {}
  const showStudySheet = include.studySheet !== false
  const showFlashcards = include.flashcards !== false
  const showAnswers = include.answers !== false
  const showNotes = include.notes !== false

  const blocks = Array.isArray(payload.blocks) ? payload.blocks : []
  const lessons = Array.isArray(payload.lessons) ? payload.lessons : []
  const flashcards = Array.isArray(payload.flashcards) ? payload.flashcards : []
  const quizzes = Array.isArray(payload.quizzes) ? payload.quizzes : []

  let lessonHtml = ''
  if (showStudySheet && (blocks.length > 0 || lessons.length > 0)) {
    const items = blocks.length > 0 ? blocks : lessons
    lessonHtml = items
      .map(
        (l: { type?: string; content?: string; title?: string; front?: string; back?: string; question?: string }) => {
          if ((l as { front?: string }).front !== undefined) return ''
          return `<div class="block"><h3>${(l as { title?: string })?.title ?? 'Section'}</h3><div class="content">${String((l as { content?: string })?.content ?? '').replace(/\n/g, '<br>')}</div></div>`
        }
      )
      .filter(Boolean)
      .join('')
  }

  let flashcardHtml = ''
  if (showFlashcards && flashcards.length > 0) {
    flashcardHtml = flashcards
      .map(
        (f: { front?: string; back?: string }) =>
          `<div class="flashcard"><div class="front">${(f as { front?: string })?.front ?? ''}</div><div class="back">${(f as { back?: string })?.back ?? ''}</div></div>`
      )
      .join('')
  }

  let quizHtml = ''
  if (showAnswers && quizzes.length > 0) {
    quizHtml = quizzes
      .map(
        (q: { question?: string; options?: string[]; correctIndex?: number }) => {
          const opts = (q as { options?: string[] })?.options ?? []
          const idx = (q as { correctIndex?: number })?.correctIndex ?? 0
          const answer = opts[idx] ?? ''
          return `<div class="quiz"><p class="question">${(q as { question?: string })?.question ?? ''}</p><p class="answer">Answer: ${answer}</p></div>`
        }
      )
      .join('')
  }

  const watermarkClass = opts.watermark ? ' watermark' : ''
  const paperW = opts.paperSize === 'Letter' ? '8.5in' : opts.paperSize === 'Legal' ? '8.5in' : '210mm'
  const paperH = opts.paperSize === 'Letter' ? '11in' : opts.paperSize === 'Legal' ? '14in' : '297mm'

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${study.topic ?? 'Study'} - StudySpark</title>
  <style>
    @page { size: ${paperW} ${paperH}; margin: 1in; }
    body { font-family: Inter, Nunito, system-ui, sans-serif; max-width: 100%; margin: 0; padding: 24px; color: rgb(35,35,35); }
    .watermark { position: relative; }
    .watermark::after { content: "StudySpark - Preview"; position: fixed; top: 50%; left: 50%; transform: translate(-50%,-50%) rotate(-30deg); font-size: 48px; color: rgba(169,166,249,0.2); pointer-events: none; }
    h1 { color: rgb(91, 87, 165); }
    .block, .flashcard, .quiz { margin: 16px 0; padding: 16px; border-radius: 12px; background: rgb(255,249,242); border: 1px solid rgb(232,230,240); }
    .flashcard { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
    .front, .back { padding: 12px; background: white; border-radius: 8px; }
    @media print { body { padding: 0; } .block, .flashcard, .quiz { break-inside: avoid; } }
  </style>
</head>
<body class="${watermarkClass}">
  <h1>${study.topic ?? 'Study'}</h1>
  <p>Generated by StudySpark</p>
  ${lessonHtml ? `<section><h2>Study Sheet</h2>${lessonHtml}</section>` : ''}
  ${flashcardHtml ? `<section><h2>Flashcards</h2><div class="flashcards">${flashcardHtml}</div></section>` : ''}
  ${quizHtml ? `<section><h2>Answer Key</h2>${quizHtml}</section>` : ''}
</body>
</html>`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(
        JSON.stringify({ message: 'Missing authorization' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    )

    const { data: { user }, error: authError } = await supabase.auth.getUser(
      authHeader.replace('Bearer ', '')
    )
    if (authError || !user) {
      return new Response(
        JSON.stringify({ message: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const body = (await req.json().catch(() => ({}))) as Record<string, unknown>
    const studyId = (body?.studyId ?? '').toString()
    const exportType = ((body?.exportType ?? 'pdf') as string) === 'bundle' ? 'bundle' : 'pdf'
    const paperSize = (['A4', 'Letter', 'Legal'].includes((body?.paperSize as string) ?? '') ? body.paperSize : 'A4') as PaperSize
    const orientation = ((body?.orientation as string) ?? 'portrait') === 'landscape' ? 'landscape' : 'portrait'
    const watermark = Boolean(body?.watermark)
    const include = (body?.include as IncludedSections) ?? {}

    if (!studyId) {
      return new Response(
        JSON.stringify({ message: 'studyId required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { data: study, error: studyErr } = await supabase
      .from('studies')
      .select('id, topic')
      .eq('id', studyId)
      .eq('user_id', user.id)
      .single()

    if (studyErr || !study) {
      return new Response(
        JSON.stringify({ message: 'Study not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { data: draftRow } = await supabase
      .from('drafts')
      .select('content_payload')
      .eq('study_id', studyId)
      .single()

    const payload = (draftRow?.content_payload as Record<string, unknown>) ?? {}

    const { data: insertRow, error: insertErr } = await supabase
      .from('exports')
      .insert({
        user_id: user.id,
        study_id: studyId,
        export_type: exportType,
        status: 'processing',
        progress: 10,
        watermark_enabled: watermark,
        paper_size: paperSize,
        orientation,
        included_sections: {
          studySheet: include.studySheet !== false,
          flashcards: include.flashcards !== false,
          answers: include.answers !== false,
          notes: include.notes !== false,
        },
      })
      .select('id')
      .single()

    if (insertErr || !insertRow) {
      return new Response(
        JSON.stringify({ message: insertErr?.message ?? 'Failed to create export' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const jobId = String(insertRow.id)

    const html = renderExportHtml(study, payload, {
      watermark,
      paperSize,
      orientation,
      include: {
        studySheet: include.studySheet !== false,
        flashcards: include.flashcards !== false,
        answers: include.answers !== false,
        notes: include.notes !== false,
      },
    })

    const safeName = (study.topic ?? 'study').replace(/[^a-z0-9]/gi, '-')
    const filename = `${safeName}_${Date.now()}.html`

    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
    const downloadUrl = `${supabaseUrl}/functions/v1/exports-download?jobId=${jobId}`

    const { error: updateErr } = await supabase
      .from('exports')
      .update({
        status: 'completed',
        progress: 100,
        result_data: html,
        result_url: downloadUrl,
        updated_at: new Date().toISOString(),
      })
      .eq('id', jobId)
      .eq('user_id', user.id)

    if (updateErr) {
      await supabase
        .from('exports')
        .update({ status: 'failed', error_message: updateErr.message, updated_at: new Date().toISOString() })
        .eq('id', jobId)
        .eq('user_id', user.id)
      return new Response(
        JSON.stringify({ message: updateErr.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    return new Response(
      JSON.stringify({ jobId, status: 'completed' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (err) {
    return new Response(
      JSON.stringify({ message: (err as Error).message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
