/**
 * Supabase Edge Function: studies-export
 * Exports study as printable HTML or PDF.
 * POST /functions/v1/studies-export
 * Body: { studyId, format: 'html' | 'pdf' }
 * Returns: HTML string (format=html) or PDF blob (format=pdf)
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

function renderHtml(study: { topic?: string }, payload: Record<string, unknown>): string {
  const lessons = Array.isArray(payload.lessons) ? payload.lessons : []
  const flashcards = Array.isArray(payload.flashcards) ? payload.flashcards : []
  const quizzes = Array.isArray(payload.quizzes) ? payload.quizzes : []

  const lessonHtml = lessons
    .map(
      (l: { type?: string; content?: string; title?: string }) =>
        `<div class="block"><h3>${(l as { title?: string })?.title ?? 'Section'}</h3><div class="content">${String((l as { content?: string })?.content ?? '').replace(/\n/g, '<br>')}</div></div>`
    )
    .join('')

  const flashcardHtml = flashcards
    .map(
      (f: { front?: string; back?: string }) =>
        `<div class="flashcard"><div class="front">${(f as { front?: string })?.front ?? ''}</div><div class="back">${(f as { back?: string })?.back ?? ''}</div></div>`
    )
    .join('')

  const quizHtml = quizzes
    .map(
      (q: { question?: string; options?: string[] }) =>
        `<div class="quiz"><p class="question">${(q as { question?: string })?.question ?? ''}</p><ul>${((q as { options?: string[] })?.options ?? []).map((o) => `<li>${o}</li>`).join('')}</ul></div>`
    )
    .join('')

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${study.topic ?? 'Study'} - StudySpark</title>
  <style>
    body { font-family: Inter, system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #232323; }
    h1 { color: rgb(91, 87, 165); }
    .block, .flashcard, .quiz { margin: 16px 0; padding: 16px; border-radius: 12px; background: #FFF9F2; border: 1px solid #E8E6F0; }
    .flashcard { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
    .front, .back { padding: 12px; background: white; border-radius: 8px; }
    @media print { body { padding: 0; } .block, .flashcard, .quiz { break-inside: avoid; } }
  </style>
</head>
<body>
  <h1>${study.topic ?? 'Study'}</h1>
  <p>Generated by StudySpark</p>
  ${lessonHtml ? `<section><h2>Lessons</h2>${lessonHtml}</section>` : ''}
  ${flashcardHtml ? `<section><h2>Flashcards</h2><div class="flashcards">${flashcardHtml}</div></section>` : ''}
  ${quizHtml ? `<section><h2>Quiz</h2>${quizHtml}</section>` : ''}
</body>
</html>`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const url = new URL(req.url)
    const studyIdParam = url.searchParams.get('studyId')
    const formatParam = url.searchParams.get('format')

    let studyId = ''
    let format: 'html' | 'pdf' = 'html'

    if (req.method === 'GET' && studyIdParam) {
      studyId = studyIdParam
      format = formatParam === 'pdf' ? 'pdf' : 'html'
    } else if (req.method === 'POST') {
      const body = await req.json().catch(() => ({}))
      studyId = (body?.studyId ?? '').toString()
      format = (body?.format ?? 'html').toString() === 'pdf' ? 'pdf' : 'html'
    }

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(
        JSON.stringify({ message: 'Missing authorization' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    )

    const { data: { user }, error: authError } = await supabase.auth.getUser(
      authHeader.replace('Bearer ', '')
    )
    if (authError || !user) {
      return new Response(
        JSON.stringify({ message: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    if (!studyId) {
      return new Response(
        JSON.stringify({ message: 'studyId required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { data: study, error: studyErr } = await supabase
      .from('studies')
      .select('id, topic')
      .eq('id', studyId)
      .eq('user_id', user.id)
      .single()

    if (studyErr || !study) {
      return new Response(
        JSON.stringify({ message: 'Study not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { data: draftRow } = await supabase
      .from('drafts')
      .select('content_payload')
      .eq('study_id', studyId)
      .single()

    const payload = (draftRow?.content_payload as Record<string, unknown>) ?? {}
    const html = renderHtml(study, payload)

    if (format === 'pdf') {
      return new Response(
        JSON.stringify({ message: 'PDF export requires a PDF service. Use format=html and convert client-side.' }),
        { status: 501, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    return new Response(html, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `inline; filename="${(study.topic ?? 'study').replace(/[^a-z0-9]/gi, '-')}.html"`,
      },
    })
  } catch (err) {
    return new Response(
      JSON.stringify({ message: (err as Error).message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
